BEGIN;

UPDATE bible.books SET book_name = 'GENESIS', short_name = 'Gen.' WHERE id = 206;
UPDATE bible.books SET book_name = 'EXODUS', short_name = 'Ex.' WHERE id = 207;
UPDATE bible.books SET book_name = 'LEVITICUS', short_name = 'Lev.' WHERE id = 208;
UPDATE bible.books SET book_name = 'NUMBERS', short_name = 'Num.' WHERE id = 209;
UPDATE bible.books SET book_name = 'DEUTERONOMY', short_name = 'Deut.' WHERE id = 210;
UPDATE bible.books SET book_name = 'JOSUA', short_name = 'Jos.' WHERE id = 211;
UPDATE bible.books SET book_name = 'RORELTUTE', short_name = 'Ro.' WHERE id = 212;
UPDATE bible.books SET book_name = 'RUTHI', short_name = 'Rut.' WHERE id = 213;
UPDATE bible.books SET book_name = '1 SAMUELA', short_name = '1Sam.' WHERE id = 214;
UPDATE bible.books SET book_name = '2 SAMUELA', short_name = '2Sam.' WHERE id = 215;
UPDATE bible.books SET book_name = '1 LALTE', short_name = '1Lal.' WHERE id = 216;
UPDATE bible.books SET book_name = '2 LALTE', short_name = '2Lal.' WHERE id = 217;
UPDATE bible.books SET book_name = '1 CHRONICLES', short_name = '1Chro.' WHERE id = 218;
UPDATE bible.books SET book_name = '2 CHRONICLES', short_name = '2Chro.' WHERE id = 219;
UPDATE bible.books SET book_name = 'EZRA', short_name = 'Ezr.' WHERE id = 220;
UPDATE bible.books SET book_name = 'NEHEMIA', short_name = 'Neh.' WHERE id = 221;
UPDATE bible.books SET book_name = 'ESTHERI', short_name = 'Est.' WHERE id = 222;
UPDATE bible.books SET book_name = 'JOBA', short_name = 'Job.' WHERE id = 223;
UPDATE bible.books SET book_name = 'SAM', short_name = 'Sam.' WHERE id = 224;
UPDATE bible.books SET book_name = 'THUFINGTE', short_name = 'Thuf.' WHERE id = 225;
UPDATE bible.books SET book_name = 'THUHRILTU', short_name = 'Thur.' WHERE id = 226;
UPDATE bible.books SET book_name = 'SOLOMONA HLATE', short_name = 'Sol.H.' WHERE id = 227;
UPDATE bible.books SET book_name = 'ISAIA', short_name = 'Is.' WHERE id = 228;
UPDATE bible.books SET book_name = 'JEREMIA', short_name = 'Jer.' WHERE id = 229;
UPDATE bible.books SET book_name = 'ṬAH HLA', short_name = 'TH' WHERE id = 230;
UPDATE bible.books SET book_name = 'EZEKIELA', short_name = 'Ezek.' WHERE id = 231;
UPDATE bible.books SET book_name = 'DANIELA', short_name = 'Dan.' WHERE id = 232;
UPDATE bible.books SET book_name = 'HOSEA', short_name = 'Hos.' WHERE id = 233;
UPDATE bible.books SET book_name = 'JOELA', short_name = 'Joel.' WHERE id = 234;
UPDATE bible.books SET book_name = 'AMOSA', short_name = 'Amos.' WHERE id = 235;
UPDATE bible.books SET book_name = 'OBADIA', short_name = 'Obad.' WHERE id = 236;
UPDATE bible.books SET book_name = 'JONA', short_name = 'Jon.' WHERE id = 237;
UPDATE bible.books SET book_name = 'MIKA', short_name = 'Mik.' WHERE id = 238;
UPDATE bible.books SET book_name = 'NAHUMA', short_name = 'Nahum.' WHERE id = 239;
UPDATE bible.books SET book_name = 'HABAKUKA', short_name = 'Hab.' WHERE id = 240;
UPDATE bible.books SET book_name = 'ZEPHANIA', short_name = 'Zep.' WHERE id = 241;
UPDATE bible.books SET book_name = 'HAGGAIA', short_name = 'Hag.' WHERE id = 242;
UPDATE bible.books SET book_name = 'ZAKARIA', short_name = 'Zak.' WHERE id = 243;
UPDATE bible.books SET book_name = 'MALAKIA', short_name = 'Mal.' WHERE id = 244;
UPDATE bible.books SET book_name = 'MATTHAIA', short_name = 'Mt.' WHERE id = 245;
UPDATE bible.books SET book_name = 'MARKA', short_name = 'Mk.' WHERE id = 246;
UPDATE bible.books SET book_name = 'LUKA', short_name = 'Lk.' WHERE id = 247;
UPDATE bible.books SET book_name = 'JOHANA', short_name = 'Joh.' WHERE id = 248;
UPDATE bible.books SET book_name = 'TIRHKOHTE', short_name = 'Tirh.' WHERE id = 249;
UPDATE bible.books SET book_name = 'ROM', short_name = 'Rom.' WHERE id = 250;
UPDATE bible.books SET book_name = '1 KORINTH', short_name = '1Kor.' WHERE id = 251;
UPDATE bible.books SET book_name = '2 KORINTH', short_name = '2Kor.' WHERE id = 252;
UPDATE bible.books SET book_name = 'GALATIA', short_name = 'Gal.' WHERE id = 253;
UPDATE bible.books SET book_name = 'EPHESI', short_name = 'Eph.' WHERE id = 254;
UPDATE bible.books SET book_name = 'PHILIPPI', short_name = 'Phil.' WHERE id = 255;
UPDATE bible.books SET book_name = 'KOLOSA', short_name = 'Kol.' WHERE id = 256;
UPDATE bible.books SET book_name = '1 THESSALONIKA', short_name = '1Thes.' WHERE id = 257;
UPDATE bible.books SET book_name = '2 THESSALONIKA', short_name = '2Thes.' WHERE id = 258;
UPDATE bible.books SET book_name = '1 TIMOTHEA', short_name = '1Tim.' WHERE id = 259;
UPDATE bible.books SET book_name = '2 TIMOTHEA', short_name = '2Tim.' WHERE id = 260;
UPDATE bible.books SET book_name = 'TITA', short_name = 'Tit.' WHERE id = 261;
UPDATE bible.books SET book_name = 'PHILEMONA', short_name = 'Philm.' WHERE id = 262;
UPDATE bible.books SET book_name = 'HEBRAI', short_name = 'Heb.' WHERE id = 263;
UPDATE bible.books SET book_name = 'JAKOBA', short_name = 'Jak.' WHERE id = 264;
UPDATE bible.books SET book_name = '1 PETERA', short_name = '1Pet.' WHERE id = 265;
UPDATE bible.books SET book_name = '2 PETERA', short_name = '2Pet.' WHERE id = 266;
UPDATE bible.books SET book_name = '1 JOHANA', short_name = '1Joh.' WHERE id = 267;
UPDATE bible.books SET book_name = '2 JOHANA', short_name = '2Joh.' WHERE id = 268;
UPDATE bible.books SET book_name = '3 JOHANA', short_name = '3Joh.' WHERE id = 269;
UPDATE bible.books SET book_name = 'JUDA', short_name = 'Jud.' WHERE id = 270;
UPDATE bible.books SET book_name = 'THUPUAN', short_name = 'Thup.' WHERE id = 271;

COMMIT;
